name: Generate Doxygen Docs

on:
  push:
    tags:
      - 'v*'  

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen

    - name: Run Doxygen
      run: doxygen Doxyfile

    - name: Upload Doxygen HTML as artifact
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-docs
        path: html/
